using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpawnBullets : MonoBehaviour
{
    public GameObject bullet;
    public float repeatInterval = 0.1f;
    public float flipInterval = 1f;
    public int offsetCounter = 0;
    public int offset = 4;
    public bool reversing = false;
    public float bulletCount = 10;
    public bool spiral = true;
    private int direction = 1;
    // Start is called before the first frame update
    void Start()
    {
        InvokeRepeating("SpawnWave", 1f, repeatInterval);
        if(reversing){
            InvokeRepeating("FlipDirection", 1f, flipInterval);
        }
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void SpawnWave(){        

        // offset counter and offset to make spiral, offset counter is the current wave and offset is the distance difference between each wave
        for(int i = 0; i < bulletCount; i++){
            // angle in RADIANS generated by max spread and modified by offset for spirals
            float angle = Mathf.Deg2Rad * ((360f/bulletCount) * i + offset * offsetCounter * direction);
            float angleX = Mathf.Cos(angle);
            float angleY = Mathf.Sin(angle);
            Vector3 temp = new Vector3(angleX,0f,angleY);
            Quaternion rotation = Quaternion.LookRotation(temp, Vector3.up);

            // currently spawning on the parent object
            Instantiate(bullet, gameObject.transform.position, rotation);
        }
        if(spiral){
            offsetCounter++;
        }
        
    }
    private void FlipDirection(){
        direction*= -1;
    }
}
